Network:
  epochs: 200
  pre_epochs: 50
  batch_size: 250
  n_steps: 16 # timestep
  class_num: [10,26,10,10]
  seed: [42]
  dataset: ['KMNIST','Letters', 'FashionMNIST', 'MNIST']
  ood_data: ['KMNIST', 'FashionMNIST', 'MNIST', 'Letters', 'not_MNIST', 'CIFAR10_BW','MNIST-square'] ## can be ['MNIST','FMNIST','KMNIST','Letters','not_MNIST','CIFAR10_BW','MNIST-square','MNIST-C/brightness','MNIST-C/canny_edges','MNIST-C/dotted_line', 'MNIST-C/fog','MNIST-C/glass_blur','MNIST-C/identity','MNIST-C/impulse_noise','MNIST-C/motion_blur','MNIST-C/rotate', 'MNIST-C/scale','MNIST-C/shear', 'MNIST-C/shot_noise','MNIST-C/spatter', 'MNIST-C/stripe','MNIST-C/translate', 'MNIST-C/zigzag']
  in_channels: 1
  data_path: "../SNN-AD/Datasets"
  lr: 0.001
  n_class: 10
  latent_dim: 128
  input_size: 32
  model: "FSVAE" # FSVAE or  FSVAE_large
  k: 20 # multiplier of channel
  scheduled: true # whether to apply scheduled sampling
  loss_func: 'mmd' # mmd or kld


